language: python
python:
  - "3.6"
install:
  - export PYTHONPATH=${PYTHONPATH}:.
  #- pip install -e .
# Run tests
script:
  - pip install -r requirements.test.txt
  - pip install codecov
  - pytest --cov=.
  - codecov
